export const STOCK_INDICES = {
  NIFTY_50: [
    "RELIANCE",
    "TCS",
    "INFY",
    "HDFCBANK",
    "ICICIBANK",
    "HINDUNILVR",
    "KOTAKBANK",
    "SBIN",
    "ITC",
    "BHARTIARTL",
    "WIPRO",
    "AXISBANK",
    "MARUTI",
    "LT",
    "SUNPHARMA",
    "TITAN",
    "BAJFINANCE",
    "ONGC",
    "NTPC",
    "POWERGRID",
    "HCLTECH",
    "ULTRACEMCO",
    "ASIANPAINT",
    "BAJAJFINSV",
    "COALINDIA",
    "M&M",
    "TECHM",
    "HDFCLIFE",
    "INDUSINDBK",
    "TATASTEEL",
    "NESTLEIND",
    "JSWSTEEL",
    "DRREDDY",
    "ADANIPORTS",
    "GRASIM",
    "CIPLA",
    "BPCL",
    "DIVISLAB",
    "SBILIFE",
    "BRITANNIA",
    "EICHERMOT",
    "UPL",
    "SHREECEM",
    "HEROMOTOCO",
    "TATAMOTORS",
    "IOC",
    "BAJAJ-AUTO",
    "HINDALCO",
  ],
  NIFTY_BANK: [
    "HDFCBANK",
    "ICICIBANK",
    "KOTAKBANK",
    "AXISBANK",
    "SBIN",
    "INDUSINDBK",
    "BANDHANBNK",
  ],
} as const;

export type IndexType = keyof typeof STOCK_INDICES;
